version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /integration-tests/tracecontext/docker
    schedule:
      interval: daily
